### ISSUE TITLE
Add license info

### ISSUE THREAD

**Issue by OverloadUT** [respectTheCode/node-isy#1]
I am interested in using and potentially forking this project, but there is no license listed.

**Comment by OverloadUT** [comment]
Never mind - I see that the license is in the package file!

**Comment by respectTheCode** [comment]
I had big plans for this module but haven't had the time to get anywhere with it. If you do end up forking it I will gladly accept pull requests.

**Comment by OverloadUT** [comment]
I wrote my own implementation before I realized the license can be in the package file, but it's less complete than this, so I will migrate over to my own fork of this and begin adding some features.
